# Use the official Node.js 18 image
FROM node:20

# Create and change to the app directory.
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Copy the source files
COPY . .

# Command to start the app in development mode
CMD ["npm", "run", "dev"]
