# fly.toml app configuration file generated for afp-modelo-backend on 2024-07-20T20:23:15-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'afp-modelo-backend'
primary_region = 'scl'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[env]
  AFP_MODELO_RUT="199474928"
  POSTGRES_PORT="5432"