name: POST request with curl to load data

on:
  schedule:
    - cron: '0 13 * * *'
  workflow_run:
    workflows: ["Deploy to Fly.io"]
    types:
      - completed

jobs:
  curl_post_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send POST request
        env:
          POST_URL: ${{ vars.LOAD_DATA_URL }}
        run: |
          curl -X POST $POST_URL -H "Content-Type: application/json"
